<?php

namespace App\Support;

/**
 * Temporary sample data for the Builder Dashboard frontend.
 * Replace this with Eloquent / MySQL via the controller later.
 */
class DemoDashboardData
{
    public static function shell(): array
    {
        return [
            'builder' => [
                'name' => 'Skyline Builders',
                'role' => 'Premium Partner',
                'initials' => 'SK',
            ],
            'navItems' => [
                ['id' => 'overview', 'label' => 'Overview', 'icon' => 'layout', 'route' => 'dashboard'],
                ['id' => 'projects', 'label' => 'Projects', 'icon' => 'building', 'route' => 'builder.projects'],
                ['id' => 'listings', 'label' => 'Listings', 'icon' => 'home', 'route' => 'builder.listings'],
                ['id' => 'leads', 'label' => 'Leads', 'icon' => 'users', 'route' => 'builder.leads'],
                ['id' => 'bargain', 'label' => 'Smart Bargain', 'icon' => 'handshake', 'route' => 'builder.bargain'],
                ['id' => 'ads', 'label' => 'Ads & Promotions', 'icon' => 'megaphone', 'route' => 'builder.ads'],
                ['id' => 'analytics', 'label' => 'Analytics', 'icon' => 'chart', 'route' => 'builder.analytics'],
                ['id' => 'documents', 'label' => 'Documents', 'icon' => 'file', 'route' => 'builder.documents'],
            ],
            'footItems' => [
                ['id' => 'notifications', 'label' => 'Notifications', 'icon' => 'bell', 'route' => 'builder.notifications'],
                ['id' => 'settings', 'label' => 'Settings', 'icon' => 'settings', 'route' => 'builder.settings'],
            ],
        ];
    }

    public static function all(): array
    {
        return array_merge(self::shell(), [
            'stats' => [
                ['label' => 'Active Projects', 'value' => '8', 'trend' => '+12% vs last month', 'dir' => 'up', 'icon' => 'building', 'tone' => 'mint'],
                ['label' => 'Total Units Listed', 'value' => '342', 'trend' => '+8% vs last month', 'dir' => 'up', 'icon' => 'home', 'tone' => 'sky'],
                ['label' => 'New Leads (Today)', 'value' => '24', 'trend' => '+15% vs last month', 'dir' => 'up', 'icon' => 'phone', 'tone' => 'green'],
                ['label' => 'Active Bargain Deals', 'value' => '12', 'trend' => '-5% vs last month', 'dir' => 'down', 'icon' => 'handshake', 'tone' => 'peach'],
                ['label' => 'Units Sold', 'value' => '156', 'trend' => '+23% vs last month', 'dir' => 'up', 'icon' => 'check', 'tone' => 'lime'],
                ['label' => 'Ads Running', 'value' => '5', 'trend' => '0% vs last month', 'dir' => 'flat', 'icon' => 'megaphone', 'tone' => 'rose'],
            ],
            'leads' => [
                [
                    'name' => 'Rahul Sharma',
                    'initials' => 'RS',
                    'color' => '#dbeafe',
                    'ink' => '#2563eb',
                    'property' => 'Sky Heights - 3BHK',
                    'status' => 'New',
                    'statusClass' => 'chip-new',
                    'email' => 'rahul.s****@gmail.com',
                    'phone' => '+91 98****45678',
                    'place' => 'Mumbai, Maharashtra',
                    'when' => 'Today, 2:30 PM',
                ],
                [
                    'name' => 'Priya Patel',
                    'initials' => 'PP',
                    'color' => '#dcfce7',
                    'ink' => '#16a34a',
                    'property' => 'Green Valley - 2BHK',
                    'status' => 'Contacted',
                    'statusClass' => 'chip-contacted',
                    'email' => 'priya.p****@yahoo.com',
                    'phone' => '+91 87****12345',
                    'place' => 'Pune, Maharashtra',
                    'when' => 'Today, 11:15 AM',
                ],
                [
                    'name' => 'Amit Kumar',
                    'initials' => 'AK',
                    'color' => '#ffedd5',
                    'ink' => '#ea580c',
                    'property' => 'Urban Edge - 4BHK',
                    'status' => 'Site Visit',
                    'statusClass' => 'chip-visit',
                    'email' => 'amit.k****@gmail.com',
                    'phone' => '+91 99****67890',
                    'place' => 'Bangalore, Karnataka',
                    'when' => 'Yesterday, 4:00 PM',
                ],
            ],
            'activity' => [
                ['icon' => 'userPlus', 'tone' => 'mint', 'title' => 'New lead received', 'desc' => 'Rahul Sharma inquired about Sky Heights 3BHK', 'time' => '2 minutes ago'],
                ['icon' => 'send', 'tone' => 'sky', 'title' => 'Counter offer sent', 'desc' => 'You countered ₹1.62 Cr for Sky Heights A-1204', 'time' => '1 hour ago'],
                ['icon' => 'check', 'tone' => 'lime', 'title' => 'Unit sold!', 'desc' => 'Green Valley B-302 marked as sold', 'time' => '3 hours ago'],
                ['icon' => 'file', 'tone' => 'peach', 'title' => 'Pending approval', 'desc' => 'Urban Edge Phase 2 awaiting admin review', 'time' => '5 hours ago'],
                ['icon' => 'alert', 'tone' => 'rose', 'title' => 'Ad campaign expiring', 'desc' => 'Featured listing for Sky Heights expires in 2 days', 'time' => 'Yesterday'],
            ],
            'deals' => [
                [
                    'id' => 'B001',
                    'title' => 'Sky Heights Tower A',
                    'unit' => 'Unit SH-A-1204',
                    'status' => 'Counter Sent',
                    'statusClass' => 'chip-counter',
                    'buyer' => '₹1.55 Cr',
                    'counter' => '₹1.62 Cr',
                    'expires' => null,
                ],
                [
                    'id' => 'B002',
                    'title' => 'Green Valley Block B',
                    'unit' => 'Unit GV-B-505',
                    'status' => 'Awaiting Response',
                    'statusClass' => 'chip-wait',
                    'buyer' => '₹85.00 L',
                    'counter' => null,
                    'expires' => 'Expires in 4 hours',
                ],
            ],
            'hotUnits' => [
                ['name' => 'Sky Heights A-1204', 'meta' => '234 views • 12 inquiries', 'rank' => 1],
                ['name' => 'Green Valley B-505', 'meta' => '189 views • 8 inquiries', 'rank' => 2],
                ['name' => 'Urban Edge C-1801', 'meta' => '156 views • 6 inquiries', 'rank' => 3],
            ],
            'banner' => [
                'title' => '2 projects pending approval',
                'text' => 'Urban Edge Phase 2 and Riverside Gardens are awaiting admin review',
            ],
        ]);
    }

    public static function projects(): array
    {
        return array_merge(self::shell(), [
            'projectFilters' => ['All', 'Active', 'Pending', 'Completed'],
            'projects' => [
                [
                    'name' => 'Sky Heights',
                    'location' => 'Andheri West, Mumbai',
                    'status' => 'Active',
                    'statusClass' => 'chip-live',
                    'totalUnits' => 120,
                    'sold' => 89,
                    'available' => 31,
                    'progress' => 74,
                    'leads' => 45,
                    'rera' => 'P51900000001',
                ],
                [
                    'name' => 'Green Valley',
                    'location' => 'Whitefield, Bangalore',
                    'status' => 'Active',
                    'statusClass' => 'chip-live',
                    'totalUnits' => 85,
                    'sold' => 52,
                    'available' => 33,
                    'progress' => 61,
                    'leads' => 32,
                    'rera' => 'P52100000456',
                ],
                [
                    'name' => 'Urban Edge',
                    'location' => 'Hinjewadi, Pune',
                    'status' => 'Pending Approval',
                    'statusClass' => 'chip-pending',
                    'totalUnits' => 200,
                    'sold' => 0,
                    'available' => 200,
                    'progress' => 0,
                    'leads' => 18,
                    'rera' => 'Pending',
                ],
                [
                    'name' => 'Palm Residences',
                    'location' => 'Bandra East, Mumbai',
                    'status' => 'Active',
                    'statusClass' => 'chip-live',
                    'totalUnits' => 60,
                    'sold' => 48,
                    'available' => 12,
                    'progress' => 80,
                    'leads' => 28,
                    'rera' => 'P51900000789',
                ],
                [
                    'name' => 'Lake View Towers',
                    'location' => 'Powai, Mumbai',
                    'status' => 'Completed',
                    'statusClass' => 'chip-completed',
                    'totalUnits' => 150,
                    'sold' => 150,
                    'available' => 0,
                    'progress' => 100,
                    'leads' => 0,
                    'rera' => 'P51900000234',
                ],
                [
                    'name' => 'Metro Heights',
                    'location' => 'Koramangala, Bangalore',
                    'status' => 'Pending Approval',
                    'statusClass' => 'chip-pending',
                    'totalUnits' => 95,
                    'sold' => 0,
                    'available' => 95,
                    'progress' => 0,
                    'leads' => 12,
                    'rera' => 'Pending',
                ],
            ],
        ]);
    }

    public static function leadsPage(): array
    {
        return array_merge(self::shell(), [
            'leadMetrics' => [
                ['label' => 'Total Leads', 'value' => '6'],
                ['label' => 'New', 'value' => '2'],
                ['label' => 'Contacted', 'value' => '1'],
                ['label' => 'Site Visits', 'value' => '1'],
                ['label' => 'Negotiating', 'value' => '1'],
                ['label' => 'Closed', 'value' => '1'],
            ],
            'leadFilters' => ['All', 'New', 'Contacted', 'Site Visit', 'Closed'],
            'leadProjects' => ['All Projects', 'Sky Heights', 'Green Valley', 'Urban Edge'],
            'managementLeads' => [
                [
                    'name' => 'Rahul Sharma',
                    'initials' => 'RS',
                    'color' => '#dbeafe',
                    'ink' => '#2563eb',
                    'email' => 'rahul.s****@gmail.com',
                    'phone' => '+91 98***45678',
                    'project' => 'Sky Heights',
                    'unit' => '3BHK - A-1204',
                    'status' => 'New',
                    'statusClass' => 'chip-new',
                    'source' => 'Website',
                    'date' => 'Jan 17, 2026',
                    'showActions' => true,
                ],
                [
                    'name' => 'Priya Patel',
                    'initials' => 'PP',
                    'color' => '#dcfce7',
                    'ink' => '#16a34a',
                    'email' => 'priya.p****@yahoo.com',
                    'phone' => '+91 87***12345',
                    'project' => 'Green Valley',
                    'unit' => '2BHK - B-505',
                    'status' => 'Contacted',
                    'statusClass' => 'chip-contacted',
                    'source' => 'Facebook Ad',
                    'date' => 'Jan 17, 2026',
                    'showActions' => false,
                ],
                [
                    'name' => 'Amit Kumar',
                    'initials' => 'AK',
                    'color' => '#ffedd5',
                    'ink' => '#ea580c',
                    'email' => 'amit.k****@gmail.com',
                    'phone' => '+91 99***67890',
                    'project' => 'Urban Edge',
                    'unit' => '4BHK - C-1801',
                    'status' => 'Site Visit',
                    'statusClass' => 'chip-visit',
                    'source' => 'Google Ad',
                    'date' => 'Jan 16, 2026',
                    'showActions' => false,
                ],
                [
                    'name' => 'Sneha Reddy',
                    'initials' => 'SR',
                    'color' => '#ccfbf1',
                    'ink' => '#0f766e',
                    'email' => 'sneha.r****@gmail.com',
                    'phone' => '+91 90***33421',
                    'project' => 'Sky Heights',
                    'unit' => '2BHK - B-302',
                    'status' => 'Negotiating',
                    'statusClass' => 'chip-negotiating',
                    'source' => 'Referral',
                    'date' => 'Jan 15, 2026',
                    'showActions' => false,
                ],
                [
                    'name' => 'Vikram Singh',
                    'initials' => 'VS',
                    'color' => '#dcfce7',
                    'ink' => '#15803d',
                    'email' => 'vikram.s****@outlook.com',
                    'phone' => '+91 88***11223',
                    'project' => 'Green Valley',
                    'unit' => '3BHK - A-701',
                    'status' => 'Closed',
                    'statusClass' => 'chip-closed',
                    'source' => 'Website',
                    'date' => 'Jan 14, 2026',
                    'showActions' => false,
                ],
                [
                    'name' => 'Anjali Mehta',
                    'initials' => 'AM',
                    'color' => '#e0e7ff',
                    'ink' => '#4338ca',
                    'email' => 'anjali.m****@gmail.com',
                    'phone' => '+91 97***55667',
                    'project' => 'Urban Edge',
                    'unit' => '3BHK - D-1502',
                    'status' => 'New',
                    'statusClass' => 'chip-new',
                    'source' => 'Instagram',
                    'date' => 'Jan 17, 2026',
                    'showActions' => false,
                ],
            ],
        ]);
    }

    public static function settings(): array
    {
        return array_merge(self::shell(), [
            'settingsTabs' => [
                ['id' => 'profile', 'label' => 'Profile', 'icon' => 'user'],
                ['id' => 'company', 'label' => 'Company', 'icon' => 'building'],
                ['id' => 'notifications', 'label' => 'Notifications', 'icon' => 'bell'],
                ['id' => 'security', 'label' => 'Security', 'icon' => 'shield'],
            ],
            'profile' => [
                'initials' => 'SK',
                'firstName' => 'Suresh',
                'lastName' => 'Kumar',
                'email' => 'suresh@skylinebuilders.com',
                'phone' => '+91 98765 43210',
            ],
            'company' => [
                'name' => 'Skyline Builders Pvt. Ltd.',
                'gst' => '27AAAAA0000A1Z5',
                'pan' => 'AAAAA0000A',
                'address' => '123, Business Park, Andheri East, Mumbai - 400069',
                'website' => 'www.skylinebuilders.com',
                'year' => '2005',
            ],
            'notificationPrefs' => [
                ['label' => 'New Lead Alerts', 'desc' => 'Get notified when you receive a new lead inquiry', 'on' => true],
                ['label' => 'Bargain Responses', 'desc' => 'Notifications for buyer counter-offers and responses', 'on' => true],
                ['label' => 'Approval Updates', 'desc' => 'Unit and project approval status changes', 'on' => true],
                ['label' => 'Ad Campaign Alerts', 'desc' => 'Campaign expiry and performance notifications', 'on' => true],
                ['label' => 'Document Reminders', 'desc' => 'Expiry reminders for RERA and other documents', 'on' => true],
                ['label' => 'Email Notifications', 'desc' => 'Receive notifications via email', 'on' => true],
                ['label' => 'SMS Notifications', 'desc' => 'Receive important alerts via SMS', 'on' => false],
            ],
        ]);
    }

    public static function notificationsPage(): array
    {
        return array_merge(self::shell(), [
            'notificationFilters' => [
                ['label' => 'All', 'badge' => null],
                ['label' => 'Unread', 'badge' => 3],
                ['label' => 'Leads', 'badge' => null],
                ['label' => 'Bargains', 'badge' => null],
            ],
            'unreadCount' => 3,
            'notifications' => [
                [
                    'title' => 'New lead received',
                    'desc' => 'Rahul Sharma inquired about Sky Heights 3BHK (A-1204).',
                    'time' => '2 minutes ago',
                    'icon' => 'phone',
                    'tone' => 'teal',
                    'category' => 'leads',
                    'unread' => true,
                    'showActions' => false,
                ],
                [
                    'title' => 'Bargain response pending',
                    'desc' => 'Buyer countered ₹1.55 Cr for Sky Heights A-1204. Expires in 4 hours.',
                    'time' => '1 hour ago',
                    'icon' => 'message',
                    'tone' => 'teal',
                    'category' => 'bargains',
                    'unread' => true,
                    'showActions' => true,
                ],
                [
                    'title' => 'Unit approved',
                    'desc' => 'Urban Edge C-1801 has been approved by admin and is now live.',
                    'time' => '3 hours ago',
                    'icon' => 'file',
                    'tone' => 'green',
                    'category' => 'all',
                    'unread' => true,
                    'showActions' => false,
                ],
                [
                    'title' => 'Ad campaign expiring',
                    'desc' => 'Sky Heights Launch campaign expires in 2 days. Renew to continue visibility.',
                    'time' => '5 hours ago',
                    'icon' => 'megaphone',
                    'tone' => 'orange',
                    'category' => 'all',
                    'unread' => false,
                    'showActions' => false,
                ],
                [
                    'title' => 'Document expiry reminder',
                    'desc' => 'Fire NOC for Green Valley expires next month. Please renew.',
                    'time' => 'Yesterday',
                    'icon' => 'alert',
                    'tone' => 'red',
                    'category' => 'all',
                    'unread' => false,
                    'showActions' => false,
                ],
                [
                    'title' => 'Deal closed successfully',
                    'desc' => 'Sale agreement for Sky Heights B-302 has been signed by the buyer.',
                    'time' => 'Yesterday',
                    'icon' => 'check',
                    'tone' => 'green',
                    'category' => 'bargains',
                    'unread' => false,
                    'showActions' => false,
                ],
                [
                    'title' => 'Site visit scheduled',
                    'desc' => 'Amit Kumar has confirmed site visit for Urban Edge on Jan 18 at 11 AM.',
                    'time' => '2 days ago',
                    'icon' => 'calendar',
                    'tone' => 'sky',
                    'category' => 'leads',
                    'unread' => false,
                    'showActions' => false,
                ],
                [
                    'title' => 'Project pending approval',
                    'desc' => 'Riverside Gardens is awaiting admin approval. Expected review in 24 hours.',
                    'time' => '2 days ago',
                    'icon' => 'building',
                    'tone' => 'navy',
                    'category' => 'all',
                    'unread' => false,
                    'showActions' => false,
                ],
            ],
        ]);
    }

    public static function listings(): array
    {
        return array_merge(self::shell(), [
            'listingFilters' => ['All', 'Available', 'On Hold', 'Sold'],
            'listingProjects' => ['All Projects', 'Sky Heights', 'Green Valley', 'Urban Edge', 'Palm Residences'],
            'listings' => [
                [
                    'unitId' => 'SH-A-1204',
                    'project' => 'Sky Heights',
                    'type' => '3BHK',
                    'size' => '1,450 sq.ft',
                    'price' => '₹1.65 Cr',
                    'status' => 'Available',
                    'statusClass' => 'chip-available',
                    'leads' => 12,
                    'views' => 234,
                ],
                [
                    'unitId' => 'GV-B-505',
                    'project' => 'Green Valley',
                    'type' => '2BHK',
                    'size' => '1,100 sq.ft',
                    'price' => '₹85 L',
                    'status' => 'On Hold',
                    'statusClass' => 'chip-hold',
                    'leads' => 8,
                    'views' => 189,
                ],
                [
                    'unitId' => 'UE-C-1801',
                    'project' => 'Urban Edge',
                    'type' => '4BHK',
                    'size' => '2,200 sq.ft',
                    'price' => '₹2.40 Cr',
                    'status' => 'Pending Approval',
                    'statusClass' => 'chip-approval',
                    'leads' => 6,
                    'views' => 156,
                ],
                [
                    'unitId' => 'SH-B-302',
                    'project' => 'Sky Heights',
                    'type' => '2BHK',
                    'size' => '980 sq.ft',
                    'price' => '₹1.10 Cr',
                    'status' => 'Sold',
                    'statusClass' => 'chip-sold-gray',
                    'leads' => 0,
                    'views' => 412,
                ],
                [
                    'unitId' => 'PR-A-701',
                    'project' => 'Palm Residences',
                    'type' => '3BHK',
                    'size' => '1,320 sq.ft',
                    'price' => '₹1.45 Cr',
                    'status' => 'Available',
                    'statusClass' => 'chip-available',
                    'leads' => 15,
                    'views' => 278,
                ],
                [
                    'unitId' => 'GV-A-120',
                    'project' => 'Green Valley',
                    'type' => '3BHK',
                    'size' => '1,380 sq.ft',
                    'price' => '₹1.05 Cr',
                    'status' => 'On Hold',
                    'statusClass' => 'chip-hold',
                    'leads' => 4,
                    'views' => 97,
                ],
                [
                    'unitId' => 'SH-C-905',
                    'project' => 'Sky Heights',
                    'type' => '4BHK',
                    'size' => '2,050 sq.ft',
                    'price' => '₹2.15 Cr',
                    'status' => 'Available',
                    'statusClass' => 'chip-available',
                    'leads' => 9,
                    'views' => 201,
                ],
                [
                    'unitId' => 'UE-D-402',
                    'project' => 'Urban Edge',
                    'type' => '2BHK',
                    'size' => '1,050 sq.ft',
                    'price' => '₹95 L',
                    'status' => 'Sold',
                    'statusClass' => 'chip-sold-gray',
                    'leads' => 0,
                    'views' => 320,
                ],
            ],
        ]);
    }

    public static function ads(): array
    {
        return array_merge(self::shell(), [
            'adMetrics' => [
                ['label' => 'Total Impressions', 'value' => '49.0K', 'icon' => 'eye', 'tone' => 'sky'],
                ['label' => 'Total Clicks', 'value' => '1,276', 'icon' => 'cursor', 'tone' => 'mint'],
                ['label' => 'Avg. CTR', 'value' => '2.60%', 'icon' => 'trendUp', 'tone' => 'peach'],
                ['label' => 'Total Spent', 'value' => '₹138.5K', 'icon' => 'calendar', 'tone' => 'lavender'],
            ],
            'campaignFilters' => ['All Campaigns', 'Active', 'Paused', 'Completed'],
            'campaigns' => [
                [
                    'name' => 'Sky Heights Launch',
                    'meta' => 'Sky Heights • Featured Listing',
                    'status' => 'Active',
                    'statusClass' => 'chip-available',
                    'impressions' => '18.2K',
                    'clicks' => '524',
                    'ctr' => '2.88%',
                    'spent' => '₹35.0K',
                    'budget' => '₹50.0K',
                    'progress' => 70,
                    'start' => 'Jan 1, 2026',
                    'end' => 'Jan 31, 2026',
                ],
                [
                    'name' => 'Green Valley Promo',
                    'meta' => 'Green Valley • Social Ads',
                    'status' => 'Paused',
                    'statusClass' => 'chip-hold',
                    'impressions' => '9.4K',
                    'clicks' => '210',
                    'ctr' => '2.23%',
                    'spent' => '₹18.5K',
                    'budget' => '₹40.0K',
                    'progress' => 46,
                    'start' => 'Dec 15, 2025',
                    'end' => 'Jan 15, 2026',
                ],
                [
                    'name' => 'Urban Edge Boost',
                    'meta' => 'Urban Edge • Search Ads',
                    'status' => 'Active',
                    'statusClass' => 'chip-available',
                    'impressions' => '14.8K',
                    'clicks' => '390',
                    'ctr' => '2.64%',
                    'spent' => '₹42.0K',
                    'budget' => '₹60.0K',
                    'progress' => 70,
                    'start' => 'Jan 5, 2026',
                    'end' => 'Feb 5, 2026',
                ],
                [
                    'name' => 'Palm Residences Ad',
                    'meta' => 'Palm Residences • Retargeting',
                    'status' => 'Completed',
                    'statusClass' => 'chip-sold-gray',
                    'impressions' => '6.6K',
                    'clicks' => '152',
                    'ctr' => '2.30%',
                    'spent' => '₹43.0K',
                    'budget' => '₹43.0K',
                    'progress' => 100,
                    'start' => 'Nov 1, 2025',
                    'end' => 'Nov 30, 2025',
                ],
            ],
        ]);
    }

    public static function analytics(): array
    {
        return array_merge(self::shell(), [
            'analyticsRanges' => ['7 Days', '30 Days', '90 Days', '1 Year'],
            'analyticsStats' => [
                ['label' => 'Total Leads', 'value' => '372', 'trend' => '+16.7%', 'dir' => 'up', 'icon' => 'users', 'tone' => 'mint'],
                ['label' => 'Total Views', 'value' => '12.4K', 'trend' => '+24.3%', 'dir' => 'up', 'icon' => 'eye', 'tone' => 'sky'],
                ['label' => 'Conversion Rate', 'value' => '28.4%', 'trend' => '-2.1%', 'dir' => 'down', 'icon' => 'percent', 'tone' => 'peach'],
                ['label' => 'Revenue (Ads)', 'value' => '₹2.4L', 'trend' => '+8.5%', 'dir' => 'up', 'icon' => 'rupee', 'tone' => 'lime'],
            ],
            'leadTrend' => [
                'labels' => ['Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan'],
                'values' => [42, 50, 58, 70, 78, 88],
                'max' => 100,
            ],
            'conversionFunnel' => [
                'labels' => ['Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan'],
                'series' => [
                    ['key' => 'inquiries', 'color' => '#131d34', 'values' => [78, 82, 75, 88, 90, 92]],
                    ['key' => 'siteVisits', 'color' => '#30b5a6', 'values' => [48, 52, 50, 58, 62, 65]],
                    ['key' => 'closed', 'color' => '#22c55e', 'values' => [18, 22, 20, 28, 30, 34]],
                ],
                'max' => 100,
            ],
            'projectPerformance' => [
                'labels' => ['Sky Heights', 'Green Valley', 'Urban Edge', 'Sunrise Apts'],
                'series' => [
                    ['key' => 'leads', 'color' => '#131d34', 'values' => [62, 48, 74, 36]],
                    ['key' => 'conversion', 'color' => '#30b5a6', 'values' => [28, 22, 34, 18]],
                ],
                'max' => 80,
            ],
            'cityDemand' => [
                ['label' => 'Mumbai', 'value' => 38, 'color' => '#30b5a6'],
                ['label' => 'Bangalore', 'value' => 27, 'color' => '#131d34'],
                ['label' => 'Pune', 'value' => 20, 'color' => '#f97316'],
                ['label' => 'Delhi NCR', 'value' => 15, 'color' => '#22c55e'],
            ],
            'bargainRate' => [
                ['label' => 'Accepted', 'value' => 52, 'color' => '#22c55e'],
                ['label' => 'Rejected', 'value' => 28, 'color' => '#ef4444'],
                ['label' => 'Pending', 'value' => 20, 'color' => '#f97316'],
            ],
        ]);
    }

    public static function documents(): array
    {
        return array_merge(self::shell(), [
            'documentBanner' => [
                'title' => '1 document pending verification',
                'text' => 'Urban Edge RERA Certificate is awaiting admin approval.',
            ],
            'documentTabs' => [
                ['id' => 'rera', 'label' => 'RERA Certificates'],
                ['id' => 'approval', 'label' => 'Approval Letters'],
                ['id' => 'agreements', 'label' => 'Agreements'],
            ],
            'documents' => [
                [
                    'title' => 'Sky Heights RERA Certificate',
                    'project' => 'Sky Heights',
                    'idLabel' => 'RERA ID',
                    'idValue' => 'P51900000001',
                    'status' => 'Verified',
                    'statusClass' => 'chip-verified',
                    'statusIcon' => 'checkSimple',
                    'expires' => 'Dec 2027',
                    'category' => 'rera',
                ],
                [
                    'title' => 'Green Valley RERA Certificate',
                    'project' => 'Green Valley',
                    'idLabel' => 'RERA ID',
                    'idValue' => 'P52100000456',
                    'status' => 'Verified',
                    'statusClass' => 'chip-verified',
                    'statusIcon' => 'checkSimple',
                    'expires' => 'Mar 2028',
                    'category' => 'rera',
                ],
                [
                    'title' => 'Urban Edge RERA Certificate',
                    'project' => 'Urban Edge',
                    'idLabel' => 'RERA ID',
                    'idValue' => 'Pending',
                    'status' => 'Pending',
                    'statusClass' => 'chip-doc-pending',
                    'statusIcon' => 'clock',
                    'expires' => 'Pending',
                    'category' => 'rera',
                ],
                [
                    'title' => 'Sky Heights Approval Letter',
                    'project' => 'Sky Heights',
                    'idLabel' => 'Ref',
                    'idValue' => 'APL-SH-2025-014',
                    'status' => 'Verified',
                    'statusClass' => 'chip-verified',
                    'statusIcon' => 'checkSimple',
                    'expires' => 'Jun 2028',
                    'category' => 'approval',
                ],
                [
                    'title' => 'Palm Residences Approval Letter',
                    'project' => 'Palm Residences',
                    'idLabel' => 'Ref',
                    'idValue' => 'APL-PR-2025-009',
                    'status' => 'Pending',
                    'statusClass' => 'chip-doc-pending',
                    'statusIcon' => 'clock',
                    'expires' => 'Pending',
                    'category' => 'approval',
                ],
                [
                    'title' => 'Buyer Agreement Template',
                    'project' => 'All Projects',
                    'idLabel' => 'Doc',
                    'idValue' => 'AGR-GEN-001',
                    'status' => 'Verified',
                    'statusClass' => 'chip-verified',
                    'statusIcon' => 'checkSimple',
                    'expires' => 'No expiry',
                    'category' => 'agreements',
                ],
                [
                    'title' => 'Sky Heights Sale Agreement',
                    'project' => 'Sky Heights',
                    'idLabel' => 'Doc',
                    'idValue' => 'AGR-SH-A-1204',
                    'status' => 'Verified',
                    'statusClass' => 'chip-verified',
                    'statusIcon' => 'checkSimple',
                    'expires' => 'Jan 2027',
                    'category' => 'agreements',
                ],
            ],
        ]);
    }
}
